# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 224f9e7c11f9361cebcb9394564ea8d44f9bddd58899e7ad8abebb8d1ea2210f2a138862cc492fd63a16c86d3ae5754275eabf4a3b70f5208ff2b509b9392f58

test:
  secret_key_base: 599abff0ce0879db0bf61fa2b0ee29f215223c40eb59c911f1f11ac6687355148121cdd68f4f8b40d794fbe0cee1ee646ae798ff72626e7e2ec5b27ff8234ac8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
